//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class kormyshevEntities : DbContext
    {


        private static kormyshevEntities _context;

        public static kormyshevEntities GetContext()
        {
            if (_context == null)
            {
                _context = new kormyshevEntities();
            }
            return _context;
        }

        public kormyshevEntities()
            : base("name=kormyshevEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Category1> Category1 { get; set; }
        public virtual DbSet<Discount1> Discount1 { get; set; }
        public virtual DbSet<Product1> Product1 { get; set; }
        public virtual DbSet<Role1> Role1 { get; set; }
        public virtual DbSet<Sell1> Sell1 { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
    }
}
