//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell1
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int UserId { get; set; }
        public int SellId { get; set; }
    
        public virtual Discount1 Discount1 { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
